services:
  - type: web
    name: gearguard-app
    env: python
    runtime: python-3.11.8
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn gearguard_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: gearguard-db
          property: connectionString
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false

databases:
  - name: gearguard-db
    databaseName: gearguard
    plan: free